#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "usage: $0 <version> <release>"
    exit 1
fi

keyring="keyring"
if [ ! -z "$2" ]; then
    keyring="$2"
fi

dir="$(dirname "$0")"
dir="$(cd "${dir}"; pwd)"

base="$(dirname "${dir}")"
version="$1"
release="$2"
release="${release//_/+}"
name="wharfrat"

sed_script="s|@@version@@|${version}-${release}|g;s|@@name@@|${name}|g;s|@@package@@|${name}|g"

echo "Build ${name} DEB: v${version}-${release}"

echo

echo "Run some checks ..."
dpkgdeb="$(which dpkg-deb 2>/dev/null)"
if [ -z "${dpkgdeb}" ]; then
    echo "  unable to find dpkg-deb!"
    exit 1
fi

echo "Create build tree ..."
scratch="${dir}/deb-scratch"
rm -rf "${scratch}"
mkdir -p "${scratch}"
mkdir -p "${scratch}/DEBIAN"
mkdir -p "${scratch}/usr/bin"
mkdir -p "${scratch}/usr/share/doc/${name}"
mkdir -p "${scratch}/usr/share/lintian/overrides"

echo "Create control file ..."
sed -e "${sed_script}" "${dir}/template.control" > "${scratch}/DEBIAN/control"

echo "Collate files ..."

cp "${base}/dist/${name}" "${scratch}/usr/bin/"
ln -s "wharfrat" "${scratch}/usr/bin/wr"

cp "${base}/LICENSE" "${scratch}/usr/share/doc/${package}/copyright"
#cp "${base}/README.md" "${scratch}/usr/share/doc/${package}/"

cp "${dir}/lintian" "${scratch}/usr/share/lintian/overrides/${package}"

echo "Fix permissions ..."
find "${scratch}" -type f -exec chmod 644 {} \;
find "${scratch}" -type d -exec chmod 755 {} \;
find "${scratch}/usr/bin" -type f -exec chmod 755 {} \;
find "${scratch}/DEBIAN" -name "pre*" -exec chmod 755 {} \;
find "${scratch}/DEBIAN" -name "post*" -exec chmod 755 {} \;

echo "Run dpkg-deb ..."
mkdir -p "${dir}/debs"
fakeroot dpkg-deb --build "${scratch}" "${dir}/debs"
